# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: soywod
open_collective: soywod
ko_fi: soywod
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: soywod
issuehunt: soywod
otechie: soywod
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
